version: "2.1"

services:
    example:
        container_name: example
        image: example
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            USE_MONGODB: "false"
            USE_REDIS: "false"
        ports:
            - 80:80
        logging:
            options:
                max-size: 50m
        env_file:
            - ./.env
